# Generated by Django 4.0.1 on 2022-01-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0003_boss_hp_boss_maxhp_houses_housepoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss',
            old_name='maxhp',
            new_name='max_hp',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='housename',
            new_name='house_name',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='housepoints',
            new_name='house_points',
        ),
    ]
