# Generated by Django 4.0.1 on 2022-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0004_rename_maxhp_boss_max_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boss',
            name='max_hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_points',
            field=models.IntegerField(null=True),
        ),
    ]
