# Generated by Django 4.0.1 on 2022-01-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0005_alter_boss_hp_alter_boss_max_hp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss',
            old_name='max_hp',
            new_name='maxhp',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='house_name',
            new_name='housename',
        ),
        migrations.RenameField(
            model_name='houses',
            old_name='house_points',
            new_name='housepoints',
        ),
    ]
