# Generated by Django 4.0.1 on 2022-01-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0006_rename_max_hp_boss_maxhp_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boss',
            table='boss',
        ),
        migrations.AlterModelTable(
            name='houses',
            table='houses',
        ),
    ]
